site_name: The Library Of Shaders
site_description: Copyright and license free library of shaders and explanations to empower developers to learn shader development
repo_url: https://github.com/Snorfield/The-Library-Of-Shaders

extra_css:
  - css/custom.css

theme:
  name: mkdocs
  user_color_mode_toggle: false
  color_mode: dark
  custom_dir: docs/theme/


nav:
  - Home: index.md

  - Shaders:
      - Vertex Shaders:
        - Index: Vertex/index.md

      - Fragment Shaders:
        - Index: Fragment/index.md

      - Post Processing:
        - Index: PostProcessing/index.md
        - Chromatic Aberration: PostProcessing/ChromaticAberration.md
        - Bloom: PostProcessing/Bloom.md
        - Vignette: PostProcessing/Vignette.md
        - Gaussian Blur: PostProcessing/GaussianBlur.md


  - Resources:
      - Index: resources/index.md

      - Godot 4.X: resources/godot.md
