site_name: The Library Of Shaders
extra_css:
  - css/custom.css

theme:
  name: mkdocs
  user_color_mode_toggle: false
  color_mode: dark
  custom_dir: docs/theme/


nav:
  - Home: index.md

  - Shaders:
      - Vertex Shaders:
        - Index: Vertex/index.md

      - Fragment Shaders:
        - Index: Fragment/index.md

      - Post Processing:
        - Index: PostProcessing/index.md
        - Chromatic Aberration: PostProcessing/ChromaticAberration.md
        - Bloom: PostProcessing/Bloom.md
        - Vignette: PostProcessing/Vignette.md
        - Gaussian Blur: PostProcessing/GaussianBlur.md
